app = document.getElementById("app");
app.style.color = "blue";
app.style.backgroundColor = "red";
app.style.fontWeight = "500";
app.style.fontSize = "30px";
app.style.width = "75vw";
app.style.height ="75vh";
app.style.marginTop = "10vh";
app.style.marginLeft = "10vw";
heading-app = document.createElement("h1");
heading-app.style.textTransform = "uppercase";
heading-app.innerHTML = "aplikacja";
document.app.appenChild(heading-app);